-- MySQL Script generated by MySQL Workbench
-- Thu Sep 15 22:06:05 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dio_database
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dio_database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dio_database` DEFAULT CHARACTER SET utf8 ;
USE `dio_database` ;

-- -----------------------------------------------------
-- Table `dio_database`.`estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dio_database`.`estoque` (
  `codpro` INT NOT NULL,
  `qtdpro` INT NOT NULL,
  PRIMARY KEY (`codpro`))
-- ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dio_database`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dio_database`.`produto` (
  `codpro` INT NOT NULL AUTO_INCREMENT,
  `pronome` VARCHAR(45) NULL,
  PRIMARY KEY (`codpro`),
  UNIQUE INDEX `codpro_UNIQUE` (`codpro` ASC) VISIBLE))
-- ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dio_database`.`tipo_pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dio_database`.`tipo_pagamento` (
  `codcli` INT NOT NULL,
  `num_cartao` VARCHAR(20) NOT NULL,
  `nome_impresso` VARCHAR(45) NOT NULL,
  `bandeira` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codcli`))
-- ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dio_database`.`tipo_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dio_database`.`tipo_cliente` (
  `codcli` INT NOT NULL,
  `id_tipo` VARCHAR(2) NOT NULL,
  `tipo_cliente` VARCHAR(45) NOT NULL,
  `CPF_CNPJ` VARCHAR(45) NOT NULL,
  `tipo_clientecol` VARCHAR(45) NOT NULL,
  `tipo_pagamento_codcli` INT NOT NULL,
  PRIMARY KEY (`codcli`),
  INDEX `fk_tipo_cliente_tipo_pagamento1_idx` (`tipo_pagamento_codcli` ASC) VISIBLE,
  CONSTRAINT `fk_tipo_cliente_tipo_pagamento1`
    FOREIGN KEY (`tipo_pagamento_codcli`)
    REFERENCES `dio_database`.`tipo_pagamento` (`codcli`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
-- ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dio_database`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dio_database`.`cliente` (
  `codcli` INT NOT NULL AUTO_INCREMENT,
  `tpo` VARCHAR(2) NOT NULL,
  `nomecli` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `cep` VARCHAR(9) NOT NULL,
  `tipo_pagamento_codcli` INT NOT NULL,
  `tipo_cliente_codcli` INT NOT NULL,
  PRIMARY KEY (`codcli`),
  UNIQUE INDEX `codcli_UNIQUE` (`codcli` ASC) VISIBLE,
  UNIQUE INDEX `cpf_cnpj_UNIQUE` (`tpo` ASC) VISIBLE,
  INDEX `fk_cliente_tipo_pagamento1_idx` (`tipo_pagamento_codcli` ASC) VISIBLE,
  INDEX `fk_cliente_tipo_cliente1_idx` (`tipo_cliente_codcli` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_tipo_pagamento1`
    FOREIGN KEY (`tipo_pagamento_codcli`)
    REFERENCES `dio_database`.`tipo_pagamento` (`codcli`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_tipo_cliente1`
    FOREIGN KEY (`tipo_cliente_codcli`)
    REFERENCES `dio_database`.`tipo_cliente` (`codcli`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
-- ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dio_database`.`entrega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dio_database`.`entrega` (
  `codentrega` INT NOT NULL AUTO_INCREMENT,
  `numpedido` VARCHAR(45) NOT NULL,
  `status` VARCHAR(3) NOT NULL,
  `reatreio` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`codentrega`),
  UNIQUE INDEX `numpedido_UNIQUE` (`numpedido` ASC) VISIBLE,
  UNIQUE INDEX `codentrega_UNIQUE` (`codentrega` ASC) VISIBLE)
--ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dio_database`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dio_database`.`pedido` (
  `numpedido` INT NOT NULL,
  `codcli` VARCHAR(45) NOT NULL,
  `codpro` VARCHAR(45) NOT NULL,
  `frete` DOUBLE NOT NULL,
  `cancelado` VARCHAR(1) NOT NULL,
  `carencia` VARCHAR(1) NOT NULL,
  `pagamento` INT NOT NULL,
  `entrega_codentrega` INT NOT NULL,
  PRIMARY KEY (`numpedido`),
  INDEX `fk_pedido_entrega1_idx` (`entrega_codentrega` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_entrega1`
    FOREIGN KEY (`entrega_codentrega`)
    REFERENCES `dio_database`.`entrega` (`codentrega`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
--ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dio_database`.`fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dio_database`.`fornecedor` (
  `codforn` INT NOT NULL,
  `cnpjforn` VARCHAR(45) NOT NULL,
  `codpro` INT NOT NULL,
  `razacocial` VARCHAR(45) NOT NULL,
  `cep` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`codforn`))
--ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dio_database`.`fornece`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dio_database`.`fornece` (
  `fornecedor_codforn` INT NOT NULL,
  `produto_codpro` INT NOT NULL,
  PRIMARY KEY (`fornecedor_codforn`, `produto_codpro`),
  INDEX `fk_fornecedor_has_produto_produto1_idx` (`produto_codpro` ASC) VISIBLE,
  INDEX `fk_fornecedor_has_produto_fornecedor_idx` (`fornecedor_codforn` ASC) VISIBLE,
  CONSTRAINT `fk_fornecedor_has_produto_fornecedor`
    FOREIGN KEY (`fornecedor_codforn`)
    REFERENCES `dio_database`.`fornecedor` (`codforn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fornecedor_has_produto_produto1`
    FOREIGN KEY (`produto_codpro`)
    REFERENCES `dio_database`.`produto` (`codpro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
--ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dio_database`.`tem no estoque?`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dio_database`.`tem no estoque?` (
  `produto_codpro` INT NOT NULL,
  `estoque_codpro` INT NOT NULL,
  PRIMARY KEY (`produto_codpro`, `estoque_codpro`),
  INDEX `fk_produto_has_estoque_estoque1_idx` (`estoque_codpro` ASC) VISIBLE,
  INDEX `fk_produto_has_estoque_produto1_idx` (`produto_codpro` ASC) VISIBLE,
  CONSTRAINT `fk_produto_has_estoque_produto1`
    FOREIGN KEY (`produto_codpro`)
    REFERENCES `dio_database`.`produto` (`codpro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto_has_estoque_estoque1`
    FOREIGN KEY (`estoque_codpro`)
    REFERENCES `dio_database`.`estoque` (`codpro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
--ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dio_database`.`cliente_compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dio_database`.`cliente_compra` (
  `cliente_codcli` INT NOT NULL,
  `pedido_numpedido` INT NOT NULL,
  PRIMARY KEY (`cliente_codcli`, `pedido_numpedido`),
  INDEX `fk_cliente_has_pedido_pedido1_idx` (`pedido_numpedido` ASC) VISIBLE,
  INDEX `fk_cliente_has_pedido_cliente1_idx` (`cliente_codcli` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_has_pedido_cliente1`
    FOREIGN KEY (`cliente_codcli`)
    REFERENCES `dio_database`.`cliente` (`codcli`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_has_pedido_pedido1`
    FOREIGN KEY (`pedido_numpedido`)
    REFERENCES `dio_database`.`pedido` (`numpedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
--ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dio_database`.`pedido_contem_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dio_database`.`pedido_contem_produto` (
  `pedido_numpedido` INT NOT NULL,
  `produto_codpro` INT NOT NULL,
  PRIMARY KEY (`pedido_numpedido`, `produto_codpro`),
  INDEX `fk_pedido_has_produto_produto1_idx` (`produto_codpro` ASC) VISIBLE,
  INDEX `fk_pedido_has_produto_pedido1_idx` (`pedido_numpedido` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_has_produto_pedido1`
    FOREIGN KEY (`pedido_numpedido`)
    REFERENCES `dio_database`.`pedido` (`numpedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_has_produto_produto1`
    FOREIGN KEY (`produto_codpro`)
    REFERENCES `dio_database`.`produto` (`codpro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
--ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
