-- MySQL Script generated by MySQL Workbench
-- Thu Sep 15 23:08:07 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estoque` (
  `codpro` INT NOT NULL,
  `qtdpro` INT NOT NULL,
  PRIMARY KEY (`codpro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`produto` (
  `codpro` INT NOT NULL AUTO_INCREMENT,
  `pronome` VARCHAR(45) NULL,
  PRIMARY KEY (`codpro`),
  UNIQUE INDEX `codpro_UNIQUE` (`codpro` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_pagamento` (
  `codcli` INT NOT NULL,
  `num_cartao` VARCHAR(20) NOT NULL,
  `nome_impresso` VARCHAR(45) NOT NULL,
  `bandeira` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codcli`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_cliente` (
  `codcli` INT NOT NULL,
  `id_tipo` VARCHAR(2) NOT NULL,
  `tipo_cliente` VARCHAR(45) NOT NULL,
  `CPF_CNPJ` VARCHAR(45) NOT NULL,
  `tipo_clientecol` VARCHAR(45) NOT NULL,
  `tipo_pagamento_codcli` INT NOT NULL,
  PRIMARY KEY (`codcli`),
  INDEX `fk_tipo_cliente_tipo_pagamento1_idx` (`tipo_pagamento_codcli` ASC) VISIBLE,
  CONSTRAINT `fk_tipo_cliente_tipo_pagamento1`
    FOREIGN KEY (`tipo_pagamento_codcli`)
    REFERENCES `mydb`.`tipo_pagamento` (`codcli`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `codcli` INT NOT NULL AUTO_INCREMENT,
  `documento` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `cel` VARCHAR(9) NOT NULL,
  `email` VARCHAR(45) NULL,
  `cep` VARCHAR(10) NULL,
  `veiculo_renavam` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`codcli`),
  INDEX `fk_cliente_veiculo1_idx` (`veiculo_renavam` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_veiculo1`
    FOREIGN KEY (`veiculo_renavam`)
    REFERENCES `mydb`.`veiculo` (`renavam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`entrega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`entrega` (
  `codentrega` INT NOT NULL AUTO_INCREMENT,
  `numpedido` VARCHAR(45) NOT NULL,
  `status` VARCHAR(3) NOT NULL,
  `reatreio` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`codentrega`),
  UNIQUE INDEX `numpedido_UNIQUE` (`numpedido` ASC) VISIBLE,
  UNIQUE INDEX `codentrega_UNIQUE` (`codentrega` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pedido` (
  `numpedido` INT NOT NULL,
  `codcli` VARCHAR(45) NOT NULL,
  `codpro` VARCHAR(45) NOT NULL,
  `frete` DOUBLE NOT NULL,
  `cancelado` VARCHAR(1) NOT NULL,
  `carencia` VARCHAR(1) NOT NULL,
  `pagamento` INT NOT NULL,
  `entrega_codentrega` INT NOT NULL,
  PRIMARY KEY (`numpedido`),
  INDEX `fk_pedido_entrega1_idx` (`entrega_codentrega` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_entrega1`
    FOREIGN KEY (`entrega_codentrega`)
    REFERENCES `mydb`.`entrega` (`codentrega`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`fornecedor` (
  `codforn` INT NOT NULL,
  `cnpjforn` VARCHAR(45) NOT NULL,
  `codpro` INT NOT NULL,
  `razacocial` VARCHAR(45) NOT NULL,
  `cep` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`codforn`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`fornece`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`fornece` (
  `fornecedor_codforn` INT NOT NULL,
  `produto_codpro` INT NOT NULL,
  PRIMARY KEY (`fornecedor_codforn`, `produto_codpro`),
  INDEX `fk_fornecedor_has_produto_produto1_idx` (`produto_codpro` ASC) VISIBLE,
  INDEX `fk_fornecedor_has_produto_fornecedor_idx` (`fornecedor_codforn` ASC) VISIBLE,
  CONSTRAINT `fk_fornecedor_has_produto_fornecedor`
    FOREIGN KEY (`fornecedor_codforn`)
    REFERENCES `mydb`.`fornecedor` (`codforn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fornecedor_has_produto_produto1`
    FOREIGN KEY (`produto_codpro`)
    REFERENCES `mydb`.`produto` (`codpro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tem no estoque?`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tem no estoque?` (
  `produto_codpro` INT NOT NULL,
  `estoque_codpro` INT NOT NULL,
  PRIMARY KEY (`produto_codpro`, `estoque_codpro`),
  INDEX `fk_produto_has_estoque_estoque1_idx` (`estoque_codpro` ASC) VISIBLE,
  INDEX `fk_produto_has_estoque_produto1_idx` (`produto_codpro` ASC) VISIBLE,
  CONSTRAINT `fk_produto_has_estoque_produto1`
    FOREIGN KEY (`produto_codpro`)
    REFERENCES `mydb`.`produto` (`codpro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto_has_estoque_estoque1`
    FOREIGN KEY (`estoque_codpro`)
    REFERENCES `mydb`.`estoque` (`codpro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cliente_compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliente_compra` (
  `cliente_codcli` INT NOT NULL,
  `pedido_numpedido` INT NOT NULL,
  PRIMARY KEY (`cliente_codcli`, `pedido_numpedido`),
  INDEX `fk_cliente_has_pedido_pedido1_idx` (`pedido_numpedido` ASC) VISIBLE,
  INDEX `fk_cliente_has_pedido_cliente1_idx` (`cliente_codcli` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_has_pedido_cliente1`
    FOREIGN KEY (`cliente_codcli`)
    REFERENCES `mydb`.`cliente` (`codcli`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_has_pedido_pedido1`
    FOREIGN KEY (`pedido_numpedido`)
    REFERENCES `mydb`.`pedido` (`numpedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pedido_contem_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pedido_contem_produto` (
  `pedido_numpedido` INT NOT NULL,
  `produto_codpro` INT NOT NULL,
  PRIMARY KEY (`pedido_numpedido`, `produto_codpro`),
  INDEX `fk_pedido_has_produto_produto1_idx` (`produto_codpro` ASC) VISIBLE,
  INDEX `fk_pedido_has_produto_pedido1_idx` (`pedido_numpedido` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_has_produto_pedido1`
    FOREIGN KEY (`pedido_numpedido`)
    REFERENCES `mydb`.`pedido` (`numpedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_has_produto_produto1`
    FOREIGN KEY (`produto_codpro`)
    REFERENCES `mydb`.`produto` (`codpro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`OS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`OS` (
  `numOS` INT NOT NULL AUTO_INCREMENT,
  `renavam` VARCHAR(20) NOT NULL,
  `cod_mecanico` INT NOT NULL,
  `codpeca` INT NOT NULL,
  `codservico` INT NOT NULL,
  `valor_OS` DOUBLE NOT NULL,
  `status` VARCHAR(1) NOT NULL,
  `dt_emissao` DATE NOT NULL,
  `dr_conclusao` DATE NULL,
  `OScol` VARCHAR(45) NULL,
  PRIMARY KEY (`numOS`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`veiculo` (
  `renavam` VARCHAR(20) NOT NULL,
  `codcli` INT NOT NULL,
  `modelo` VARCHAR(45) NOT NULL,
  `tipo_veiculo` INT NOT NULL,
  `OS_numOS` INT NOT NULL,
  PRIMARY KEY (`renavam`),
  INDEX `fk_veiculo_OS1_idx` (`OS_numOS` ASC) VISIBLE,
  CONSTRAINT `fk_veiculo_OS1`
    FOREIGN KEY (`OS_numOS`)
    REFERENCES `mydb`.`OS` (`numOS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `codcli` INT NOT NULL AUTO_INCREMENT,
  `documento` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `cel` VARCHAR(9) NOT NULL,
  `email` VARCHAR(45) NULL,
  `cep` VARCHAR(10) NULL,
  `veiculo_renavam` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`codcli`),
  INDEX `fk_cliente_veiculo1_idx` (`veiculo_renavam` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_veiculo1`
    FOREIGN KEY (`veiculo_renavam`)
    REFERENCES `mydb`.`veiculo` (`renavam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`mecanico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`mecanico` (
  `cod_mecanico` INT NOT NULL AUTO_INCREMENT,
  `codservico` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `cep` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`cod_mecanico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`servicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`servicos` (
  `codservico` INT NOT NULL AUTO_INCREMENT,
  `desc` VARCHAR(100) NOT NULL,
  `valor` DOUBLE NULL,
  PRIMARY KEY (`codservico`),
  UNIQUE INDEX `valor_UNIQUE` (`valor` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pecas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pecas` (
  `codpeca` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  `valor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codpeca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pecas_da_OS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pecas_da_OS` (
  `OS_numOS` INT NOT NULL,
  `pecas_codpeca` INT NOT NULL,
  PRIMARY KEY (`OS_numOS`, `pecas_codpeca`),
  INDEX `fk_OS_has_pecas_pecas1_idx` (`pecas_codpeca` ASC) VISIBLE,
  INDEX `fk_OS_has_pecas_OS1_idx` (`OS_numOS` ASC) VISIBLE,
  CONSTRAINT `fk_OS_has_pecas_OS1`
    FOREIGN KEY (`OS_numOS`)
    REFERENCES `mydb`.`OS` (`numOS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OS_has_pecas_pecas1`
    FOREIGN KEY (`pecas_codpeca`)
    REFERENCES `mydb`.`pecas` (`codpeca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Servicos_OS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Servicos_OS` (
  `OS_numOS` INT NOT NULL,
  `servicos_codservico` INT NOT NULL,
  PRIMARY KEY (`OS_numOS`, `servicos_codservico`),
  INDEX `fk_OS_has_servicos_servicos1_idx` (`servicos_codservico` ASC) VISIBLE,
  INDEX `fk_OS_has_servicos_OS1_idx` (`OS_numOS` ASC) VISIBLE,
  CONSTRAINT `fk_OS_has_servicos_OS1`
    FOREIGN KEY (`OS_numOS`)
    REFERENCES `mydb`.`OS` (`numOS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OS_has_servicos_servicos1`
    FOREIGN KEY (`servicos_codservico`)
    REFERENCES `mydb`.`servicos` (`codservico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Especialidades Mecanico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Especialidades Mecanico` (
  `servicos_codservico` INT NOT NULL,
  `mecanico_cod_mecanico` INT NOT NULL,
  PRIMARY KEY (`servicos_codservico`, `mecanico_cod_mecanico`),
  INDEX `fk_servicos_has_mecanico_mecanico1_idx` (`mecanico_cod_mecanico` ASC) VISIBLE,
  INDEX `fk_servicos_has_mecanico_servicos1_idx` (`servicos_codservico` ASC) VISIBLE,
  CONSTRAINT `fk_servicos_has_mecanico_servicos1`
    FOREIGN KEY (`servicos_codservico`)
    REFERENCES `mydb`.`servicos` (`codservico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_servicos_has_mecanico_mecanico1`
    FOREIGN KEY (`mecanico_cod_mecanico`)
    REFERENCES `mydb`.`mecanico` (`cod_mecanico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`mecanicos_OS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`mecanicos_OS` (
  `OS_numOS` INT NOT NULL,
  `mecanico_cod_mecanico` INT NOT NULL,
  PRIMARY KEY (`OS_numOS`, `mecanico_cod_mecanico`),
  INDEX `fk_OS_has_mecanico_mecanico1_idx` (`mecanico_cod_mecanico` ASC) VISIBLE,
  INDEX `fk_OS_has_mecanico_OS1_idx` (`OS_numOS` ASC) VISIBLE,
  CONSTRAINT `fk_OS_has_mecanico_OS1`
    FOREIGN KEY (`OS_numOS`)
    REFERENCES `mydb`.`OS` (`numOS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OS_has_mecanico_mecanico1`
    FOREIGN KEY (`mecanico_cod_mecanico`)
    REFERENCES `mydb`.`mecanico` (`cod_mecanico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
